"""Auto-generated stub for IDE type checking."""

# Core exports injected by setup_params() and setup_resources()
from wetwire_aws import (
    AMI_ID,
    ARN,
    ARN_EQUALS,
    ARN_LIKE,
    ARN_NOT_EQUALS,
    ARN_NOT_LIKE,
    # AWS-specific parameter types
    AVAILABILITY_ZONE,
    # Pseudo-parameters
    AWS_ACCOUNT_ID,
    AWS_NO_VALUE,
    AWS_NOTIFICATION_ARNS,
    AWS_PARTITION,
    AWS_REGION,
    AWS_STACK_ID,
    AWS_STACK_NAME,
    AWS_URL_SUFFIX,
    # Condition operator constants
    BOOL,
    COMMA_DELIMITED_LIST,
    DATE_EQUALS,
    DATE_GREATER_THAN,
    DATE_GREATER_THAN_EQUALS,
    DATE_LESS_THAN,
    DATE_LESS_THAN_EQUALS,
    DATE_NOT_EQUALS,
    HOSTED_ZONE_ID,
    INSTANCE_ID,
    IP_ADDRESS,
    KEY_PAIR,
    LIST_AVAILABILITY_ZONE,
    LIST_NUMBER,
    LIST_SECURITY_GROUP_ID,
    LIST_SUBNET_ID,
    NOT_IP_ADDRESS,
    NULL,
    NUMBER,
    NUMERIC_EQUALS,
    NUMERIC_GREATER_THAN,
    NUMERIC_GREATER_THAN_EQUALS,
    NUMERIC_LESS_THAN,
    NUMERIC_LESS_THAN_EQUALS,
    NUMERIC_NOT_EQUALS,
    SECURITY_GROUP_ID,
    SSM_PARAMETER_STRING,
    SSM_PARAMETER_STRING_LIST,
    # Parameter type constants
    STRING,
    STRING_EQUALS,
    STRING_EQUALS_IGNORE_CASE,
    STRING_LIKE,
    STRING_NOT_EQUALS,
    STRING_NOT_EQUALS_IGNORE_CASE,
    STRING_NOT_LIKE,
    SUBNET_ID,
    VOLUME_ID,
    VPC_ID,
    And,
    Attr,
    Base64,
    Cidr,
    # Base classes
    CloudFormationResource,
    # Template components
    CloudFormationTemplate,
    Condition,
    DenyStatement,
    Equals,
    FindInMap,
    GetAtt,
    GetAZs,
    If,
    ImportValue,
    Join,
    Mapping,
    Not,
    Or,
    Output,
    Parameter,
    PolicyDocument,
    # Policy helpers
    PolicyStatement,
    PropertyType,
    # Reference types (from dataclass-dsl)
    Ref,
    RefDict,
    # Intrinsic functions
    RefIntrinsic,
    RefList,
    Select,
    Split,
    Sub,
    Tag,
    TemplateCondition,
    Transform,
    get_att,
    # Reference helpers
    ref,
    # Loader
    setup_resources,
    # Decorator
    wetwire_aws,
)
from wetwire_aws.resources import (
    accessanalyzer,
    acmpca,
    aiops,
    amazonmq,
    amplify,
    amplifyuibuilder,
    apigateway,
    apigatewayv2,
    appconfig,
    appflow,
    appintegrations,
    applicationautoscaling,
    applicationinsights,
    applicationsignals,
    appmesh,
    apprunner,
    appstream,
    appsync,
    apptest,
    aps,
    arcregionswitch,
    arczonalshift,
    ask,
    athena,
    auditmanager,
    autoscaling,
    autoscalingplans,
    b2bi,
    backup,
    backupgateway,
    batch,
    bcmdataexports,
    bedrock,
    bedrockagentcore,
    billing,
    billingconductor,
    budgets,
    cases,
    cassandra,
    ce,
    certificatemanager,
    chatbot,
    cleanrooms,
    cleanroomsml,
    cloud9,
    cloudformation,
    cloudfront,
    cloudtrail,
    cloudwatch,
    codeartifact,
    codebuild,
    codecommit,
    codeconnections,
    codedeploy,
    codeguruprofiler,
    codegurureviewer,
    codepipeline,
    codestar,
    codestarconnections,
    codestarnotifications,
    cognito,
    comprehend,
    config,
    connect,
    connectcampaigns,
    connectcampaignsv2,
    controltower,
    cur,
    customerprofiles,
    databrew,
    datapipeline,
    datasync,
    datazone,
    dax,
    deadline,
    detective,
    devopsagent,
    devopsguru,
    directoryservice,
    dlm,
    dms,
    docdb,
    docdbelastic,
    dsql,
    dynamodb,
    ec2,
    ecr,
    ecs,
    efs,
    eks,
    elasticache,
    elasticbeanstalk,
    elasticloadbalancing,
    elasticloadbalancingv2,
    elasticsearch,
    emr,
    emrcontainers,
    emrserverless,
    entityresolution,
    events,
    eventschemas,
    evidently,
    evs,
    finspace,
    fis,
    fms,
    forecast,
    frauddetector,
    fsx,
    gamelift,
    globalaccelerator,
    glue,
    grafana,
    greengrass,
    greengrassv2,
    groundstation,
    guardduty,
    healthimaging,
    healthlake,
    iam,
    identitystore,
    imagebuilder,
    inspector,
    inspectorv2,
    internetmonitor,
    invoicing,
    iot,
    iotanalytics,
    iotcoredeviceadvisor,
    iotevents,
    iotfleetwise,
    iotsitewise,
    iotthingsgraph,
    iottwinmaker,
    iotwireless,
    ivs,
    ivschat,
    kafkaconnect,
    kendra,
    kendraranking,
    kinesis,
    kinesisanalytics,
    kinesisanalyticsv2,
    kinesisfirehose,
    kinesisvideo,
    kms,
    lakeformation,
    lambda_,
    launchwizard,
    lex,
    licensemanager,
    lightsail,
    location,
    logs,
    lookoutequipment,
    lookoutvision,
    m2,
    macie,
    managedblockchain,
    mediaconnect,
    mediaconvert,
    medialive,
    mediapackage,
    mediapackagev2,
    mediastore,
    mediatailor,
    memorydb,
    mpa,
    msk,
    mwaa,
    neptune,
    neptunegraph,
    networkfirewall,
    networkmanager,
    notifications,
    notificationscontacts,
    oam,
    observabilityadmin,
    odb,
    omics,
    opensearchserverless,
    opensearchservice,
    opsworks,
    organizations,
    osis,
    panorama,
    paymentcryptography,
    pcaconnectorad,
    pcaconnectorscep,
    pcs,
    personalize,
    pinpoint,
    pinpointemail,
    pipes,
    proton,
    qbusiness,
    qldb,
    quicksight,
    ram,
    rbin,
    rds,
    redshift,
    redshiftserverless,
    refactorspaces,
    rekognition,
    resiliencehub,
    resourceexplorer2,
    resourcegroups,
    robomaker,
    rolesanywhere,
    route53,
    route53profiles,
    route53recoverycontrol,
    route53recoveryreadiness,
    route53resolver,
    rtbfabric,
    rum,
    s3,
    s3express,
    s3objectlambda,
    s3outposts,
    s3tables,
    s3vectors,
    sagemaker,
    scheduler,
    sdb,
    secretsmanager,
    securityhub,
    securitylake,
    servicecatalog,
    servicecatalogappregistry,
    servicediscovery,
    ses,
    shield,
    signer,
    simspaceweaver,
    smsvoice,
    sns,
    sqs,
    ssm,
    ssmcontacts,
    ssmguiconnect,
    ssmincidents,
    ssmquicksetup,
    sso,
    stepfunctions,
    supportapp,
    synthetics,
    systemsmanagersap,
    timestream,
    transfer,
    verifiedpermissions,
    voiceid,
    vpclattice,
    waf,
    wafregional,
    wafv2,
    wisdom,
    workspaces,
    workspacesinstances,
    workspacesthinclient,
    workspacesweb,
    xray,
)

from .bucket import LogBucket as LogBucket
from .storage import LogBucketEncryption as LogBucketEncryption
from .storage import LogBucketEncryptionDefault as LogBucketEncryptionDefault
from .storage import LogBucketEncryptionRule as LogBucketEncryptionRule
from .storage import LogBucketPublicAccessBlock as LogBucketPublicAccessBlock
from .storage import LogBucketVersioning as LogBucketVersioning

__all__: list[str] = [
    'AMI_ID', 'ARN', 'ARN_EQUALS', 'ARN_LIKE', 'ARN_NOT_EQUALS', 'ARN_NOT_LIKE',
    'AVAILABILITY_ZONE', 'AWS_ACCOUNT_ID', 'AWS_NOTIFICATION_ARNS', 'AWS_NO_VALUE',
    'AWS_PARTITION', 'AWS_REGION', 'AWS_STACK_ID', 'AWS_STACK_NAME', 'AWS_URL_SUFFIX',
    'And', 'Attr', 'BOOL', 'Base64', 'COMMA_DELIMITED_LIST', 'Cidr',
    'CloudFormationResource', 'CloudFormationTemplate', 'Condition',
    'DATE_EQUALS', 'DATE_GREATER_THAN', 'DATE_GREATER_THAN_EQUALS',
    'DATE_LESS_THAN', 'DATE_LESS_THAN_EQUALS', 'DATE_NOT_EQUALS',
    'DenyStatement', 'Equals', 'FindInMap', 'GetAZs', 'GetAtt',
    'HOSTED_ZONE_ID', 'INSTANCE_ID', 'IP_ADDRESS', 'If', 'ImportValue', 'Join',
    'KEY_PAIR', 'LIST_AVAILABILITY_ZONE', 'LIST_NUMBER', 'LIST_SECURITY_GROUP_ID',
    'LIST_SUBNET_ID', 'LogBucket', 'LogBucketEncryption', 'LogBucketEncryptionDefault',
    'LogBucketEncryptionRule', 'LogBucketPublicAccessBlock', 'LogBucketVersioning',
    'Mapping', 'NOT_IP_ADDRESS', 'NULL', 'NUMBER', 'NUMERIC_EQUALS',
    'NUMERIC_GREATER_THAN', 'NUMERIC_GREATER_THAN_EQUALS', 'NUMERIC_LESS_THAN',
    'NUMERIC_LESS_THAN_EQUALS', 'NUMERIC_NOT_EQUALS', 'Not', 'Or', 'Output',
    'Parameter', 'PolicyDocument', 'PolicyStatement', 'PropertyType',
    'Ref', 'RefDict', 'RefIntrinsic', 'RefList', 'SECURITY_GROUP_ID',
    'SSM_PARAMETER_STRING', 'SSM_PARAMETER_STRING_LIST', 'STRING',
    'STRING_EQUALS', 'STRING_EQUALS_IGNORE_CASE', 'STRING_LIKE',
    'STRING_NOT_EQUALS', 'STRING_NOT_EQUALS_IGNORE_CASE', 'STRING_NOT_LIKE',
    'SUBNET_ID', 'Select', 'Split', 'Sub', 'Tag', 'TemplateCondition', 'Transform',
    'VOLUME_ID', 'VPC_ID', 'accessanalyzer', 'acmpca', 'aiops', 'amazonmq',
    'amplify', 'amplifyuibuilder', 'apigateway', 'apigatewayv2', 'appconfig',
    'appflow', 'appintegrations', 'applicationautoscaling', 'applicationinsights',
    'applicationsignals', 'appmesh', 'apprunner', 'appstream', 'appsync', 'apptest',
    'aps', 'arcregionswitch', 'arczonalshift', 'ask', 'athena', 'auditmanager',
    'autoscaling', 'autoscalingplans', 'b2bi', 'backup', 'backupgateway', 'batch',
    'bcmdataexports', 'bedrock', 'bedrockagentcore', 'billing', 'billingconductor',
    'budgets', 'cases', 'cassandra', 'ce', 'certificatemanager', 'chatbot',
    'cleanrooms', 'cleanroomsml', 'cloud9', 'cloudformation', 'cloudfront',
    'cloudtrail', 'cloudwatch', 'codeartifact', 'codebuild', 'codecommit',
    'codeconnections', 'codedeploy', 'codeguruprofiler', 'codegurureviewer',
    'codepipeline', 'codestar', 'codestarconnections', 'codestarnotifications',
    'cognito', 'comprehend', 'config', 'connect', 'connectcampaigns',
    'connectcampaignsv2', 'controltower', 'cur', 'customerprofiles', 'databrew',
    'datapipeline', 'datasync', 'datazone', 'dax', 'deadline', 'detective',
    'devopsagent', 'devopsguru', 'directoryservice', 'dlm', 'dms', 'docdb',
    'docdbelastic', 'dsql', 'dynamodb', 'ec2', 'ecr', 'ecs', 'efs', 'eks',
    'elasticache', 'elasticbeanstalk', 'elasticloadbalancing',
    'elasticloadbalancingv2', 'elasticsearch', 'emr', 'emrcontainers',
    'emrserverless', 'entityresolution', 'events', 'eventschemas', 'evidently',
    'evs', 'finspace', 'fis', 'fms', 'forecast', 'frauddetector', 'fsx', 'gamelift',
    'get_att', 'globalaccelerator', 'glue', 'grafana', 'greengrass', 'greengrassv2',
    'groundstation', 'guardduty', 'healthimaging', 'healthlake', 'iam',
    'identitystore', 'imagebuilder', 'inspector', 'inspectorv2', 'internetmonitor',
    'invoicing', 'iot', 'iotanalytics', 'iotcoredeviceadvisor', 'iotevents',
    'iotfleetwise', 'iotsitewise', 'iotthingsgraph', 'iottwinmaker', 'iotwireless',
    'ivs', 'ivschat', 'kafkaconnect', 'kendra', 'kendraranking', 'kinesis',
    'kinesisanalytics', 'kinesisanalyticsv2', 'kinesisfirehose', 'kinesisvideo',
    'kms', 'lakeformation', 'lambda_', 'launchwizard', 'lex', 'licensemanager',
    'lightsail', 'location', 'logs', 'lookoutequipment', 'lookoutvision', 'm2',
    'macie', 'managedblockchain', 'mediaconnect', 'mediaconvert', 'medialive',
    'mediapackage', 'mediapackagev2', 'mediastore', 'mediatailor', 'memorydb',
    'mpa', 'msk', 'mwaa', 'neptune', 'neptunegraph', 'networkfirewall',
    'networkmanager', 'notifications', 'notificationscontacts', 'oam',
    'observabilityadmin', 'odb', 'omics', 'opensearchserverless', 'opensearchservice',
    'opsworks', 'organizations', 'osis', 'panorama', 'paymentcryptography',
    'pcaconnectorad', 'pcaconnectorscep', 'pcs', 'personalize', 'pinpoint',
    'pinpointemail', 'pipes', 'proton', 'qbusiness', 'qldb', 'quicksight', 'ram',
    'rbin', 'rds', 'redshift', 'redshiftserverless', 'ref', 'refactorspaces',
    'rekognition', 'resiliencehub', 'resourceexplorer2', 'resourcegroups',
    'robomaker', 'rolesanywhere', 'route53', 'route53profiles',
    'route53recoverycontrol', 'route53recoveryreadiness', 'route53resolver',
    'rtbfabric', 'rum', 's3', 's3express', 's3objectlambda', 's3outposts',
    's3tables', 's3vectors', 'sagemaker', 'scheduler', 'sdb', 'secretsmanager',
    'securityhub', 'securitylake', 'servicecatalog', 'servicecatalogappregistry',
    'servicediscovery', 'ses', 'setup_resources', 'shield', 'signer',
    'simspaceweaver', 'smsvoice', 'sns', 'sqs', 'ssm', 'ssmcontacts', 'ssmguiconnect',
    'ssmincidents', 'ssmquicksetup', 'sso', 'stepfunctions', 'supportapp',
    'synthetics', 'systemsmanagersap', 'timestream', 'transfer',
    'verifiedpermissions', 'voiceid', 'vpclattice', 'waf', 'wafregional', 'wafv2',
    'wetwire_aws', 'wisdom', 'workspaces', 'workspacesinstances',
    'workspacesthinclient', 'workspacesweb', 'xray',
]
